### ISSUE TITLE
Composer.json still has version 1.0.0

### ISSUE THREAD

**Issue by VivekShingala** [magesuite/performance#1]
Hi

Although, the version of category and product packages are moved to the new versions 1.0.1 and 1.2.3 respectively. This package's composer.json is still pointing it to version 1.0.0.

```
"creativestyle/magesuite-performance-product": "^1.0.0",
"creativestyle/magesuite-performance-category": "^1.0.0",
```

**Comment by diwipl** [comment]
Hi,
This is only a metapackage to gather related sub-packages, it would be hard for us to maintain versioning on it.

Based on constraint if any of sub-packages is updated you will get updates automatically anyway.
